# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  musiclibrary-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: musiclibrary-mysql
    volumes:
      - musiclibrary-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=musiclibrary
      - MYSQL_DATABASE=musiclibrary
      - MYSQL_USER=musiclibrary
      - MYSQL_PASSWORD=musiclibrary

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: musiclibrary-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
