version: '2'

volumes:
  musiclibrary-postgres-data:
    driver: local

services:
  postgres:
    image: postgres:10.3
    container_name: musiclibrary-postgres
    volumes:
      - musiclibrary-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=musiclibrary
      - POSTGRES_DB=musiclibrary
      - POSTGRES_USER=musiclibrary

  app:
    image: ambientum/php:7.1-caddy
    container_name: musiclibrary-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - postgres
